# .goreleaser.yaml
# The .goreleaser.yaml file is a configuration file used by Goreleaser to
# define how to build, package, and release Go projects.

version: 2
project_name: warpstream

git:
  ignore_tags:
    - "pkg/caddy/*"

builds:
  - main: ./cmd/warpstream
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch part of the filename.
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE
      - docs/*.md
      - packaging/systemd/*.service
      - packaging/windows/*.ps1
      - packaging/examples/*.yaml
      - packaging/caddy/Caddyfile

nfpms:
  - id: warpstream
    package_name: warpstream
    vendor: "DsThakurRawat"
    homepage: "https://github.com/DsThakurRawat/WarpStream"
    maintainer: "DsThakurRawat"
    description: "A Go client/server for warpstream"
    license: "MIT"
    formats:
      - deb
      - rpm
      - apk
    contents:
      - src: ./packaging/systemd/warpstream-client@.service
        dst: /usr/lib/systemd/system/warpstream-client@.service
      - src: ./packaging/systemd/warpstream-server@.service
        dst: /usr/lib/systemd/system/warpstream-server@.service

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# You can add more configuration here, e.g., for Docker images, publishing to GitHub releases, etc.
